name: Attack Validation
on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Validate PR
        if: github.event.label.name == 'attack'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          ATTACKS_DIR="attacks/$PR_NUMBER"

          # Check if problem.md exists
          if [[ ! -f "problem.md" ]]; then
            echo "::error file=problem.md::problem.md does not exist in the pull request."
            exit 1
          fi

          # Check if solution exists
          if [[ ! -f "solution" ]]; then
            echo "::error file=solution::solution file does not exist in the pull request."
            exit 1
          fi

          # Create the attacks directory if it doesn't exist
          mkdir -p "$ATTACKS_DIR"

          # Move the files to the attacks directory
          mv problem.md solution "$ATTACKS_DIR/"

          # Stage changes
          git add "$ATTACKS_DIR/problem.md" "$ATTACKS_DIR/solution"

          # Check for staged changes
          if [[ -n $(git diff --cached --exit-code) ]]; then
            # Commit the changes
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git commit -m "Organize files into $ATTACKS_DIR"

            # Push the changes back to the pull request branch
            git push
          fi

          # Merge the PR
          gh pr merge ${{ github.event.pull_request.number }} --merge
